
[canisters]

[canisters.ledger]
wasm_file = "ledger-canister.wasm"
version = "LATEST_VERSION"
sha256 = "YOUR_HASH_HERE"

[canisters.nns_governance]
wasm_file = "ic-nns-governance.wasm"
version = "LATEST_VERSION"
sha256 = "YOUR_HASH_HERE"
