name: Test Canisters

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo canisters
        uses: docker://ghcr.io/waterneuron/waterneuron@sha256:66423f63a6b9110781c134cf643088856ca141a751bc33dea0e5b8a2d1470846
        with:
          args: cargo canisters
