name: CI

on:
  push:
    branches:
      - '**'
      - 'main'

jobs:
  check:
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Run `cargo canisters`
        run: ./build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: canisters
          path: artifacts/
          retention-days: 30
