name: Podman Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Calculate Dockerfile SHA256
      id: dockerfile-sha
      run: echo "sha=$(sha256sum Dockerfile | awk '{ print $1 }')" >> $GITHUB_OUTPUT

    - name: Lowercase the repo name
      run: echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:${{ steps.dockerfile-sha.outputs.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Print event information
      run: |
        echo "Event name: ${{ github.event_name }}"
        echo "Branch name: ${{ github.head_ref || github.ref_name }}"
        echo "Target branch: ${{ github.base_ref || 'N/A' }}"
